# Generated by Django 6.0.1 on 2026-01-12 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'verbose_name': 'Book'},
        ),
        migrations.AlterModelOptions(
            name='borrow',
            options={'verbose_name': 'Borrow'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'User'},
        ),
    ]
