# Generated by Django 6.0.1 on 2026-01-12 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0002_alter_book_options_alter_borrow_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'verbose_name_plural': 'Book'},
        ),
        migrations.AlterModelOptions(
            name='borrow',
            options={'verbose_name_plural': 'Borrow'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name_plural': 'User'},
        ),
    ]
